image: quay.io/aminrf/docker-kubectl:latest

services:
  - docker:dind

stages:
  - build
  - deploy



build:
  image: docker
  stage: build
  before_script:
    - docker login -u $REGISTERY_USERNAME -p $REGISTERY_PASSWORD quay.io
  script:
    - docker build . -t quay.io/soudabe_mhashemi/ie-project:$CI_COMMIT_SHA
    - docker push quay.io/soudabe_mhashemi/ie-project:$CI_COMMIT_SHA
    - docker rmi quay.io/soudabe_mhashemi/ie-project:$CI_COMMIT_SHA || true
  after_script:
    - docker logout quay.io


deploy:
  stage: deploy
  script:
    - http_proxy=$PROXY_SERVER https_proxy=$PROXY_SERVER kubectl --kubeconfig $KUBE_CONFIG set image deployment/backend-deployment backend=quay.io/soudabe_mhashemi/ie-project:$CI_COMMIT_SHA
